{% set name = "git-annex-remote-rclone" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DanielDent/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6da12f46d46613cc5a539057052be7d8aa5259bd973ddff2d6ee460d34cd096c

build:
  number: 1
  skip: true  # [not linux]
  script: mkdir -p $PREFIX/bin && cp git-annex-remote-rclone $PREFIX/bin

requirements:
  build: []
  host:
    - bash
  run:
    - bash
    - git-annex
    - rclone

test:
  source_files:
    - tests
  commands:
    - PATH=$PWD:$PWD/tests:$PATH bash tests/all-in-one.sh

about:
  home: https://github.com/DanielDent/git-annex-remote-rclone
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Use rclone supported cloud storage providers with git-annex
  description: |
    This wrapper around rclone makes any destination supported by rclone usable
    with git-annex.
  dev_url: https://github.com/DanielDent/git-annex-remote-rclone

extra:
  recipe-maintainers:
    - DanielDent
    - yarikoptic
